name: csf_alarm
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.10.0
  flutter_datetime_picker: ^1.1.4
  fluttertoast: ^3.0.2
  shared_preferences: ^0.5.1
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/alarm.mp3
